modLoader="javafml"
loaderVersion="[32,)"

license="MIT"
issueTrackerURL="https://github.com/PaintNinja/VariableSpawnerHardness"

[[mods]]
modId="variablespawnerhardness"
version="${version}"
displayName="Variable Spawner Hardness"
displayURL="https://www.curseforge.com/minecraft/mc-mods/variable-spawner-hardness"
credits="Thanks to Conmoble and IItemstack on the MMD discord for helping make this possible."
authors="Paint_Ninja"
description='''Makes spawners take longer to destroy depending on your difficulty for a slight extra challenge.

Spawner hardnesses
------------------
Peaceful: Same hardness as vanilla (5F)
Easy: Same as end stone (9F)
Normal: Same as ender chests (22.5F)
Hard: Same as ancient debris (30F)
Hardcore: Same as obsidian (50F)

Unlike some of the blocks mentioned above, you can still destroy a spawner with any tool you want as long as you don't use your bare hands.'''

[[dependencies.variablespawnerhardness]]
modId="forge"
mandatory=true
versionRange="[32.0.72,)"
ordering="NONE"
side="BOTH"

[[dependencies.variablespawnerhardness]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"
ordering="NONE"
side="BOTH"
